---
- name: Create .ssh
  file: path=/home/{{sshuser}}/.ssh state=directory

- name: Create authorized_keys
  file: 
    path: /home/{{sshuser}}/.ssh/authorized_keys
    state: touch

- name: Change .ssh attributes
  file: 
    path: /home/{{sshuser}}/.ssh
    owner: "{{sshuser}}"
    group: "{{sshuser}}"
    mode: 700
    recursive: yes

- name: chmod the .ssh folder
  file: 
    path: /home/{{sshuser}}/.ssh/authorized_keys
    mode: 600

- name: Add the SSH key to the .ssh/authorized_keys file
  shell: echo "{{sshkey}}" >> /home/{{sshuser}}/.ssh/authorized_keys
...
