---
- name: Add an SSH key to the .ssh/authorized_keys file
  shell: mkdir /home/{{sshuser}}/.ssh
  shell: touch /home/{{sshuser}}/.ssh/authorized_keys
  shell: chown {{sshuser}}:{{sshuser}} -R .ssh
  shell: chmod 700 -R /home/{{sshuser}}/.ssh
  shell: chmod 600 /home/{{sshuser}}/.ssh/authorized_keys
  shell: echo "{{sshkey}}" >> /home/{{sshuser}}/.ssh/authorized_keys
...
